In [1]:
import os
import pandas as pd
from sklearn.model_selection import StratifiedKFold, train_test_split

# ── Config ──────────────────────────────────────────────
TRAIN_PATH   = "processed_data/df_train_clean.csv"
VAL_PATH     = "processed_data/df_val_clean.csv"
TEST_PATH    = "processed_data/df_test_clean.csv"

OUTPUT_DIR   = "./dataset/10-fold_labeled_increasing_relabel_ver3"
LABEL_COL    = "UTILIZE_LABELS"
RANDOM_STATE = 42
N_FOLDS      = 10
# ────────────────────────────────────────────────────────

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Load and combine into one pool
train_df = pd.read_csv(TRAIN_PATH)
val_df   = pd.read_csv(VAL_PATH)
test_df  = pd.read_csv(TEST_PATH)

full_df = pd.concat([train_df, val_df, test_df], axis=0).reset_index(drop=True)
print(f"Total pool: {len(full_df)} rows")
print(full_df[LABEL_COL].value_counts())

# Create 10 stratified folds
skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_STATE)
X   = full_df.index.values
y   = full_df[LABEL_COL].values

for fold_num, (train_val_idx, test_idx) in enumerate(skf.split(X, y), start=1):

    # Split train_val → train 80% / val 20%
    train_idx, val_idx = train_test_split(
        train_val_idx,
        test_size = 0.2,
        random_state = RANDOM_STATE,
        stratify = y[train_val_idx]
    )

    full_df.iloc[train_idx].reset_index(drop=True).to_csv(
        f"{OUTPUT_DIR}/algocite_utilize_dataset_train_fold_{fold_num}.csv", index=False)
    full_df.iloc[val_idx].reset_index(drop=True).to_csv(
        f"{OUTPUT_DIR}/algocite_utilize_dataset_val_fold_{fold_num}.csv", index=False)
    full_df.iloc[test_idx].reset_index(drop=True).to_csv(
        f"{OUTPUT_DIR}/algocite_utilize_dataset_test_fold_{fold_num}.csv", index=False)

    print(f"Fold {fold_num}: train={len(train_idx)}, val={len(val_idx)}, test={len(test_idx)}")

print("\nDone! Files saved to:", OUTPUT_DIR)

Total pool: 3592 rows
UTILIZE_LABELS
NOTUTILIZE    2740
UTILIZE        852
Name: count, dtype: int64
Fold 1: train=2585, val=647, test=360
Fold 2: train=2585, val=647, test=360
Fold 3: train=2586, val=647, test=359
Fold 4: train=2586, val=647, test=359
Fold 5: train=2586, val=647, test=359
Fold 6: train=2586, val=647, test=359
Fold 7: train=2586, val=647, test=359
Fold 8: train=2586, val=647, test=359
Fold 9: train=2586, val=647, test=359
Fold 10: train=2586, val=647, test=359

Done! Files saved to: ./dataset/10-fold_labeled_increasing_relabel_ver3

In [2]:
# Import required libraries
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

# Load train, test, and val dataframes
fold = 1

train_df = pd.read_csv(f'./dataset/10-fold_labeled_increasing_relabel_ver3/algocite_utilize_dataset_train_fold_{fold}.csv')
val_df = pd.read_csv(f'./dataset/10-fold_labeled_increasing_relabel_ver3/algocite_utilize_dataset_val_fold_{fold}.csv')
test_df = pd.read_csv(f'./dataset/10-fold_labeled_increasing_relabel_ver3/algocite_utilize_dataset_test_fold_{fold}.csv')

# Define the column name containing the labels for stratified sampling
label_col = 'UTILIZE_LABELS'

# Create a stratified sampler with the desired percentages
sampler = StratifiedShuffleSplit(n_splits=1, test_size=0.01, random_state=42)

# Split the train dataframe into stratified samples
for train_index, _ in sampler.split(train_df, train_df[label_col]):
    train_1percent_df = train_df.iloc[train_index[:int(len(train_index)*0.01)]]
    train_2percent_df = train_df.iloc[train_index[:int(len(train_index)*0.02)]]
    train_3percent_df = train_df.iloc[train_index[:int(len(train_index)*0.03)]]
    train_4percent_df = train_df.iloc[train_index[:int(len(train_index)*0.04)]]
    train_5percent_df = train_df.iloc[train_index[:int(len(train_index)*0.05)]]
    train_7percent_df = train_df.iloc[train_index[:int(len(train_index)*0.07)]]
    train_10percent_df = train_df.iloc[train_index[:int(len(train_index)*0.1)]]
    train_20percent_df = train_df.iloc[train_index[:int(len(train_index)*0.2)]]
    train_30percent_df = train_df.iloc[train_index[:int(len(train_index)*0.3)]]
    train_40percent_df = train_df.iloc[train_index[:int(len(train_index)*0.4)]]
    train_50percent_df = train_df.iloc[train_index[:int(len(train_index)*0.5)]]
    train_70percent_df = train_df.iloc[train_index[:int(len(train_index)*0.7)]]

# Split the test dataframe into stratified samples
for test_index, _ in sampler.split(test_df, test_df[label_col]):
    test_1percent_df = test_df.iloc[test_index[:int(len(test_index)*0.01)]]
    test_2percent_df = test_df.iloc[test_index[:int(len(test_index)*0.02)]]
    test_3percent_df = test_df.iloc[test_index[:int(len(test_index)*0.03)]]
    test_4percent_df = test_df.iloc[test_index[:int(len(test_index)*0.04)]]
    test_5percent_df = test_df.iloc[test_index[:int(len(test_index)*0.05)]]
    test_7percent_df = test_df.iloc[test_index[:int(len(test_index)*0.07)]]
    test_10percent_df = test_df.iloc[test_index[:int(len(test_index)*0.1)]]
    test_20percent_df = test_df.iloc[test_index[:int(len(test_index)*0.2)]]
    test_30percent_df = test_df.iloc[test_index[:int(len(test_index)*0.3)]]
    test_40percent_df = test_df.iloc[test_index[:int(len(test_index)*0.4)]]
    test_50percent_df = test_df.iloc[test_index[:int(len(test_index)*0.5)]]
    test_70percent_df = test_df.iloc[test_index[:int(len(test_index)*0.7)]]

# Split the validation dataframe into stratified samples
for val_index, _ in sampler.split(val_df, val_df[label_col]):
    val_1percent_df = val_df.iloc[val_index[:int(len(val_index)*0.01)]]
    val_2percent_df = val_df.iloc[val_index[:int(len(val_index)*0.02)]]
    val_3percent_df = val_df.iloc[val_index[:int(len(val_index)*0.03)]]
    val_4percent_df = val_df.iloc[val_index[:int(len(val_index)*0.04)]]
    val_5percent_df = val_df.iloc[val_index[:int(len(val_index)*0.05)]]
    val_7percent_df = val_df.iloc[val_index[:int(len(val_index)*0.07)]]
    val_10percent_df = val_df.iloc[val_index[:int(len(val_index)*0.1)]]
    val_20percent_df = val_df.iloc[val_index[:int(len(val_index)*0.2)]]
    val_30percent_df = val_df.iloc[val_index[:int(len(val_index)*0.3)]]
    val_40percent_df = val_df.iloc[val_index[:int(len(val_index)*0.4)]]
    val_50percent_df = val_df.iloc[val_index[:int(len(val_index)*0.5)]]
    val_70percent_df = val_df.iloc[val_index[:int(len(val_index)*0.7)]]

In [3]:
val_3percent_df

,contextID,citationID,clean__citation_context,UTILIZE_LABELS,USAGE_LABELS
299,6384465,6640171,"d ji . also, the graph need not be fully conne...",NOTUTILIZE,MENTION
545,96577469,91309066,igh concentration of h sions to form stable ox...,NOTUTILIZE,NOTALGO
415,4485942,4636933,rea. we can consider two main lines of researc...,NOTUTILIZE,MENTION
476,18303084,19490556,et al. 2 presented a tracking system for estim...,NOTUTILIZE,MENTION
459,201717569,239265568,bchem or any other freely accessible database....,UTILIZE,USE
465,68951215,67697387,l cw98 give an analog code construction based ...,NOTUTILIZE,MENTION
538,57052498,56384549,is approach to map the mean measured rtt betwe...,NOTUTILIZE,MENTION
302,201946319,239593487,"attenuation, the notations for p are similar, ...",UTILIZE,USE
115,201785094,239363294,e these update equations in the algorithm belo...,UTILIZE,EXTEND
245,2018358,2136061,neficial for reducing the cost and improving t...,NOTUTILIZE,NOTALGO
348,83577668,80823536,efficient constraint propagation algorithms us...,NOTUTILIZE,NOTALGO
497,11827638,12655327,d compiled in a tabular form 5 . we use the da...,NOTUTILIZE,NOTALGO
127,216312663,185930278,dood laws to punish women for refusing arrange...,NOTUTILIZE,NOTALGO
332,201670250,239199669,exists many trial routing algorithms in vlsi r...,UTILIZE,USE
84,201812480,239402553,"as msda and sda focus on feature learning, we ...",UTILIZE,USE
487,71594703,70692912,r inputs loaded into memory before running. fi...,NOTUTILIZE,MENTION
326,68941202,67685338,roblem. kuhn s method solves the problem in o(...,NOTUTILIZE,MENTION
310,23801882,24727937,is already known and can be immediately used. ...,NOTUTILIZE,MENTION
345,5750885,5952305,rithm used for re-scheduling operations we hav...,NOTUTILIZE,MENTION

In [10]:
import os

percentage = '70_percent'

# ADD THIS LINE
os.makedirs(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_{percentage}', exist_ok=True)

train_70percent_df.to_csv(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_{percentage}/algocite_utilize_dataset_train_fold_{fold}.csv', index=False)
val_70percent_df.to_csv(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_{percentage}/algocite_utilize_dataset_val_fold_{fold}.csv', index=False)
test_70percent_df.to_csv(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_{percentage}/algocite_utilize_dataset_test_fold_{fold}.csv', index=False)

In [14]:
import os

percentage = '3_percent'

# ADD THIS LINE
os.makedirs(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_{percentage}', exist_ok=True)

train_3percent_df.to_csv(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_{percentage}/algocite_utilize_dataset_train_fold_{fold}.csv', index=False)
val_3percent_df.to_csv(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_{percentage}/algocite_utilize_dataset_val_fold_{fold}.csv', index=False)
test_3percent_df.to_csv(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_{percentage}/algocite_utilize_dataset_test_fold_{fold}.csv', index=False)

In [16]:
fold = 1
percentage = '3_percent'

df_train = pd.read_csv(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_{percentage}/algocite_utilize_dataset_train_fold_{fold}.csv')
df_val = pd.read_csv(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_{percentage}/algocite_utilize_dataset_train_fold_{fold}.csv')
df_test = pd.read_csv(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_{percentage}/algocite_utilize_dataset_train_fold_{fold}.csv')
df = pd.concat([df_train, df_val, df_test], axis=0)

In [17]:
df_test['UTILIZE_LABELS'].value_counts()

UTILIZE_LABELS
NOTUTILIZE    61
UTILIZE       15
Name: count, dtype: int64

In [20]:
df_context = df[['contextID', 'citationID', 'clean__citation_context', 'UTILIZE_LABELS', 'USAGE_LABELS']].copy()
df_context

,contextID,citationID,clean__citation_context,UTILIZE_LABELS,USAGE_LABELS
0,202122274,239850671,e the most straightforward to adapt. we have u...,UTILIZE,USE
1,265138,283867,"ta. in 7 , a general classification, evaluatio...",NOTUTILIZE,MENTION
2,138591,140804,hen calculating a wcet estimate for a fact clu...,UTILIZE,EXTEND
3,10876753,11602392,simple euler scheme has proven sufficient in o...,NOTUTILIZE,MENTION
4,3424901,3528954,ble from the channel. koetter and vardy have r...,NOTUTILIZE,MENTION
...,...,...,...,...,...
71,12164628,13025216,ch of the m weights is balanced across the sub...,NOTUTILIZE,MENTION
72,108521038,100284113,"c coding based on dca (acdca),sgives 20 improv...",NOTUTILIZE,MENTION
73,63667799,62752621,"ever, similarly to the previous studies on hps...",NOTUTILIZE,MENTION
74,10902899,11633794,unity over the past decades. due to its practi...,NOTUTILIZE,MENTION
75,9622377,10199592,ource vector have approximately the same sensi...,NOTUTILIZE,MENTION

In [9]:
for fold in range(1, 11):

    df_train = pd.read_csv(f'./dataset/10-fold_labeled_increasing_relabel_ver3/algocite_utilize_dataset_train_fold_{fold}.csv')
    df_val = pd.read_csv(f'./dataset/10-fold_labeled_increasing_relabel_ver3/algocite_utilize_dataset_val_fold_{fold}.csv')
    df_test = pd.read_csv(f'./dataset/10-fold_labeled_increasing_relabel_ver3/algocite_utilize_dataset_test_fold_{fold}.csv')
    df = pd.concat([df_train, df_val, df_test], axis=0)

    df_train = df_train[['contextID', 'citationID', 'clean__citation_context', 'UTILIZE_LABELS', 'USAGE_LABELS']].copy()
    df_val = df_val[['contextID', 'citationID', 'clean__citation_context', 'UTILIZE_LABELS', 'USAGE_LABELS']].copy()
    df_test = df_test[['contextID', 'citationID', 'clean__citation_context', 'UTILIZE_LABELS', 'USAGE_LABELS']].copy()

    # df_train
    X = df_train.index
    y = df_train['UTILIZE_LABELS'].values

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=42, stratify=y)

    df_train = df_train.iloc[X_test]

    # df_val
    X = df_val.index
    y = df_val['UTILIZE_LABELS'].values

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=42, stratify=y)

    df_val = df_val.iloc[X_test]

    # df_test
    X = df_test.index
    y = df_test['UTILIZE_LABELS'].values

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=42, stratify=y)

    df_test = df_test.iloc[X_test]

    # save csv
    df_train.to_csv(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_70_percent/algocite_utilize_dataset_train_fold_{fold}.csv', index=False)
    df_val.to_csv(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_70_percent/algocite_utilize_dataset_val_fold_{fold}.csv', index=False)
    df_test.to_csv(f'./datasets2/10-fold_labeled_increasing_relabel_ver3_70_percent/algocite_utilize_dataset_test_fold_{fold}.csv', index=False)

In [12]:
import os
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

PERCENTAGES  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40, 50, 60, 70, 80, 90]
INPUT_DIR    = './dataset/10-fold_labeled_increasing_relabel_ver3'
OUTPUT_BASE  = './dataset'
LABEL_COL    = 'UTILIZE_LABELS'

for fold in range(1, 11):

    train_df = pd.read_csv(f'{INPUT_DIR}/algocite_utilize_dataset_train_fold_{fold}.csv')
    val_df   = pd.read_csv(f'{INPUT_DIR}/algocite_utilize_dataset_val_fold_{fold}.csv')
    test_df  = pd.read_csv(f'{INPUT_DIR}/algocite_utilize_dataset_test_fold_{fold}.csv')

    sampler = StratifiedShuffleSplit(n_splits=1, test_size=0.01, random_state=42)

    # get shuffled indices for each split
    for train_index, _ in sampler.split(train_df, train_df[LABEL_COL]):
        pass
    for val_index, _ in sampler.split(val_df, val_df[LABEL_COL]):
        pass
    for test_index, _ in sampler.split(test_df, test_df[LABEL_COL]):
        pass

    for percent in PERCENTAGES:
        ratio = percent / 100.0

        train_sub = train_df.iloc[train_index[:int(len(train_index) * ratio)]]
        val_sub   = val_df.iloc[val_index[:int(len(val_index) * ratio)]]
        test_sub  = test_df.iloc[test_index[:int(len(test_index) * ratio)]]

        out_dir = f'{OUTPUT_BASE}/10-fold_labeled_increasing_relabel_ver3_{percent}_percent'
        os.makedirs(out_dir, exist_ok=True)

        train_sub.to_csv(f'{out_dir}/algocite_utilize_dataset_train_fold_{fold}.csv', index=False)
        val_sub.to_csv(  f'{out_dir}/algocite_utilize_dataset_val_fold_{fold}.csv',   index=False)
        test_sub.to_csv( f'{out_dir}/algocite_utilize_dataset_test_fold_{fold}.csv',  index=False)

        print(f'Fold {fold} [{percent:>2}%]: '
              f'train={len(train_sub)} | '
              f'val={len(val_sub)} | '
              f'test={len(test_sub)}')

print('\nDone! All folds and percentages saved.')

Fold 1 [ 1%]: train=25 | val=6 | test=3
Fold 1 [ 2%]: train=51 | val=12 | test=7
Fold 1 [ 3%]: train=76 | val=19 | test=10
Fold 1 [ 4%]: train=102 | val=25 | test=14
Fold 1 [ 5%]: train=127 | val=32 | test=17
Fold 1 [ 6%]: train=153 | val=38 | test=21
Fold 1 [ 7%]: train=179 | val=44 | test=24
Fold 1 [ 8%]: train=204 | val=51 | test=28
Fold 1 [ 9%]: train=230 | val=57 | test=32
Fold 1 [10%]: train=255 | val=64 | test=35
Fold 1 [20%]: train=511 | val=128 | test=71
Fold 1 [30%]: train=767 | val=192 | test=106
Fold 1 [40%]: train=1023 | val=256 | test=142
Fold 1 [50%]: train=1279 | val=320 | test=178
Fold 1 [60%]: train=1535 | val=384 | test=213
Fold 1 [70%]: train=1791 | val=448 | test=249
Fold 1 [80%]: train=2047 | val=512 | test=284
Fold 1 [90%]: train=2303 | val=576 | test=320
Fold 2 [ 1%]: train=25 | val=6 | test=3
Fold 2 [ 2%]: train=51 | val=12 | test=7
Fold 2 [ 3%]: train=76 | val=19 | test=10
Fold 2 [ 4%]: train=102 | val=25 | test=14
Fold 2 [ 5%]: train=127 | val=32 | test=17
Fold 2 [ 6%]: train=153 | val=38 | test=21
Fold 2 [ 7%]: train=179 | val=44 | test=24
Fold 2 [ 8%]: train=204 | val=51 | test=28
Fold 2 [ 9%]: train=230 | val=57 | test=32
Fold 2 [10%]: train=255 | val=64 | test=35
Fold 2 [20%]: train=511 | val=128 | test=71
Fold 2 [30%]: train=767 | val=192 | test=106
Fold 2 [40%]: train=1023 | val=256 | test=142
Fold 2 [50%]: train=1279 | val=320 | test=178
Fold 2 [60%]: train=1535 | val=384 | test=213
Fold 2 [70%]: train=1791 | val=448 | test=249
Fold 2 [80%]: train=2047 | val=512 | test=284
Fold 2 [90%]: train=2303 | val=576 | test=320
Fold 3 [ 1%]: train=25 | val=6 | test=3
Fold 3 [ 2%]: train=51 | val=12 | test=7
Fold 3 [ 3%]: train=76 | val=19 | test=10
Fold 3 [ 4%]: train=102 | val=25 | test=14
Fold 3 [ 5%]: train=128 | val=32 | test=17
Fold 3 [ 6%]: train=153 | val=38 | test=21
Fold 3 [ 7%]: train=179 | val=44 | test=24
Fold 3 [ 8%]: train=204 | val=51 | test=28
Fold 3 [ 9%]: train=230 | val=57 | test=31
Fold 3 [10%]: train=256 | val=64 | test=35
Fold 3 [20%]: train=512 | val=128 | test=71
Fold 3 [30%]: train=768 | val=192 | test=106
Fold 3 [40%]: train=1024 | val=256 | test=142
Fold 3 [50%]: train=1280 | val=320 | test=177
Fold 3 [60%]: train=1536 | val=384 | test=213
Fold 3 [70%]: train=1792 | val=448 | test=248
Fold 3 [80%]: train=2048 | val=512 | test=284
Fold 3 [90%]: train=2304 | val=576 | test=319
Fold 4 [ 1%]: train=25 | val=6 | test=3
Fold 4 [ 2%]: train=51 | val=12 | test=7
Fold 4 [ 3%]: train=76 | val=19 | test=10
Fold 4 [ 4%]: train=102 | val=25 | test=14
Fold 4 [ 5%]: train=128 | val=32 | test=17
Fold 4 [ 6%]: train=153 | val=38 | test=21
Fold 4 [ 7%]: train=179 | val=44 | test=24
Fold 4 [ 8%]: train=204 | val=51 | test=28
Fold 4 [ 9%]: train=230 | val=57 | test=31
Fold 4 [10%]: train=256 | val=64 | test=35
Fold 4 [20%]: train=512 | val=128 | test=71
Fold 4 [30%]: train=768 | val=192 | test=106
Fold 4 [40%]: train=1024 | val=256 | test=142
Fold 4 [50%]: train=1280 | val=320 | test=177
Fold 4 [60%]: train=1536 | val=384 | test=213
Fold 4 [70%]: train=1792 | val=448 | test=248
Fold 4 [80%]: train=2048 | val=512 | test=284
Fold 4 [90%]: train=2304 | val=576 | test=319
Fold 5 [ 1%]: train=25 | val=6 | test=3
Fold 5 [ 2%]: train=51 | val=12 | test=7
Fold 5 [ 3%]: train=76 | val=19 | test=10
Fold 5 [ 4%]: train=102 | val=25 | test=14
Fold 5 [ 5%]: train=128 | val=32 | test=17
Fold 5 [ 6%]: train=153 | val=38 | test=21
Fold 5 [ 7%]: train=179 | val=44 | test=24
Fold 5 [ 8%]: train=204 | val=51 | test=28
Fold 5 [ 9%]: train=230 | val=57 | test=31
Fold 5 [10%]: train=256 | val=64 | test=35
Fold 5 [20%]: train=512 | val=128 | test=71
Fold 5 [30%]: train=768 | val=192 | test=106
Fold 5 [40%]: train=1024 | val=256 | test=142
Fold 5 [50%]: train=1280 | val=320 | test=177
Fold 5 [60%]: train=1536 | val=384 | test=213
Fold 5 [70%]: train=1792 | val=448 | test=248
Fold 5 [80%]: train=2048 | val=512 | test=284
Fold 5 [90%]: train=2304 | val=576 | test=319
Fold 6 [ 1%]: train=25 | val=6 | test=3
Fold 6 [ 2%]: train=51 | val=12 | test=7
Fold 6 [ 3%]: train=76 | val=19 | test=10
Fold 6 [ 4%]: train=102 | val=25 | test=14
Fold 6 [ 5%]: train=128 | val=32 | test=17
Fold 6 [ 6%]: train=153 | val=38 | test=21
Fold 6 [ 7%]: train=179 | val=44 | test=24
Fold 6 [ 8%]: train=204 | val=51 | test=28
Fold 6 [ 9%]: train=230 | val=57 | test=31
Fold 6 [10%]: train=256 | val=64 | test=35
Fold 6 [20%]: train=512 | val=128 | test=71
Fold 6 [30%]: train=768 | val=192 | test=106
Fold 6 [40%]: train=1024 | val=256 | test=142
Fold 6 [50%]: train=1280 | val=320 | test=177
Fold 6 [60%]: train=1536 | val=384 | test=213
Fold 6 [70%]: train=1792 | val=448 | test=248
Fold 6 [80%]: train=2048 | val=512 | test=284
Fold 6 [90%]: train=2304 | val=576 | test=319
Fold 7 [ 1%]: train=25 | val=6 | test=3
Fold 7 [ 2%]: train=51 | val=12 | test=7
Fold 7 [ 3%]: train=76 | val=19 | test=10
Fold 7 [ 4%]: train=102 | val=25 | test=14
Fold 7 [ 5%]: train=128 | val=32 | test=17
Fold 7 [ 6%]: train=153 | val=38 | test=21
Fold 7 [ 7%]: train=179 | val=44 | test=24
Fold 7 [ 8%]: train=204 | val=51 | test=28
Fold 7 [ 9%]: train=230 | val=57 | test=31
Fold 7 [10%]: train=256 | val=64 | test=35
Fold 7 [20%]: train=512 | val=128 | test=71
Fold 7 [30%]: train=768 | val=192 | test=106
Fold 7 [40%]: train=1024 | val=256 | test=142
Fold 7 [50%]: train=1280 | val=320 | test=177
Fold 7 [60%]: train=1536 | val=384 | test=213
Fold 7 [70%]: train=1792 | val=448 | test=248
Fold 7 [80%]: train=2048 | val=512 | test=284
Fold 7 [90%]: train=2304 | val=576 | test=319
Fold 8 [ 1%]: train=25 | val=6 | test=3
Fold 8 [ 2%]: train=51 | val=12 | test=7
Fold 8 [ 3%]: train=76 | val=19 | test=10
Fold 8 [ 4%]: train=102 | val=25 | test=14
Fold 8 [ 5%]: train=128 | val=32 | test=17
Fold 8 [ 6%]: train=153 | val=38 | test=21
Fold 8 [ 7%]: train=179 | val=44 | test=24
Fold 8 [ 8%]: train=204 | val=51 | test=28
Fold 8 [ 9%]: train=230 | val=57 | test=31
Fold 8 [10%]: train=256 | val=64 | test=35
Fold 8 [20%]: train=512 | val=128 | test=71
Fold 8 [30%]: train=768 | val=192 | test=106
Fold 8 [40%]: train=1024 | val=256 | test=142
Fold 8 [50%]: train=1280 | val=320 | test=177
Fold 8 [60%]: train=1536 | val=384 | test=213
Fold 8 [70%]: train=1792 | val=448 | test=248
Fold 8 [80%]: train=2048 | val=512 | test=284
Fold 8 [90%]: train=2304 | val=576 | test=319
Fold 9 [ 1%]: train=25 | val=6 | test=3
Fold 9 [ 2%]: train=51 | val=12 | test=7
Fold 9 [ 3%]: train=76 | val=19 | test=10
Fold 9 [ 4%]: train=102 | val=25 | test=14
Fold 9 [ 5%]: train=128 | val=32 | test=17
Fold 9 [ 6%]: train=153 | val=38 | test=21
Fold 9 [ 7%]: train=179 | val=44 | test=24
Fold 9 [ 8%]: train=204 | val=51 | test=28
Fold 9 [ 9%]: train=230 | val=57 | test=31
Fold 9 [10%]: train=256 | val=64 | test=35
Fold 9 [20%]: train=512 | val=128 | test=71
Fold 9 [30%]: train=768 | val=192 | test=106
Fold 9 [40%]: train=1024 | val=256 | test=142
Fold 9 [50%]: train=1280 | val=320 | test=177
Fold 9 [60%]: train=1536 | val=384 | test=213
Fold 9 [70%]: train=1792 | val=448 | test=248
Fold 9 [80%]: train=2048 | val=512 | test=284
Fold 9 [90%]: train=2304 | val=576 | test=319
Fold 10 [ 1%]: train=25 | val=6 | test=3
Fold 10 [ 2%]: train=51 | val=12 | test=7
Fold 10 [ 3%]: train=76 | val=19 | test=10
Fold 10 [ 4%]: train=102 | val=25 | test=14
Fold 10 [ 5%]: train=128 | val=32 | test=17
Fold 10 [ 6%]: train=153 | val=38 | test=21
Fold 10 [ 7%]: train=179 | val=44 | test=24
Fold 10 [ 8%]: train=204 | val=51 | test=28
Fold 10 [ 9%]: train=230 | val=57 | test=31
Fold 10 [10%]: train=256 | val=64 | test=35
Fold 10 [20%]: train=512 | val=128 | test=71
Fold 10 [30%]: train=768 | val=192 | test=106
Fold 10 [40%]: train=1024 | val=256 | test=142
Fold 10 [50%]: train=1280 | val=320 | test=177
Fold 10 [60%]: train=1536 | val=384 | test=213
Fold 10 [70%]: train=1792 | val=448 | test=248
Fold 10 [80%]: train=2048 | val=512 | test=284
Fold 10 [90%]: train=2304 | val=576 | test=319

Done! All folds and percentages saved.

In [13]:
fold = 1
df_train = pd.read_csv(f'./dataset/10-fold_labeled_increasing_relabel_ver3_50_percent/algocite_utilize_dataset_train_fold_{fold}.csv')

In [14]:
df_train = df_train[['contextID', 'citationID', 'clean__citation_context', 'UTILIZE_LABELS', 'USAGE_LABELS']].copy()
df_train

,contextID,citationID,clean__citation_context,UTILIZE_LABELS,USAGE_LABELS
0,202122274,239850671,e the most straightforward to adapt. we have u...,UTILIZE,USE
1,265138,283867,"ta. in 7 , a general classification, evaluatio...",NOTUTILIZE,MENTION
2,138591,140804,hen calculating a wcet estimate for a fact clu...,UTILIZE,EXTEND
3,10876753,11602392,simple euler scheme has proven sufficient in o...,NOTUTILIZE,MENTION
4,3424901,3528954,ble from the channel. koetter and vardy have r...,NOTUTILIZE,MENTION
...,...,...,...,...,...
1274,76729353,74989544,ard cameras that are used for person guiding. ...,NOTUTILIZE,MENTION
1275,14962704,16042770,n whether such phenomena appear in the case of...,NOTUTILIZE,MENTION
1276,126381661,113576988,"in table 1. as can be observed, the proposed a...",NOTUTILIZE,NOTALGO
1277,41726380,40117683,been studied since the early days of modern op...,NOTUTILIZE,MENTION
1278,31089639,31760334,l methods (such as the multigrid method below)...,NOTUTILIZE,MENTION

In [15]:
"""
Creates the folder structure required by Finetuning_SciBert.ipynb:

    spin-off/dataset/fold_{fold}/10-fold_original_{percent}_percent/
    ├── algocite_utilize_dataset_train_fold_{fold}.csv
    ├── algocite_utilize_dataset_val_fold_{fold}.csv
    └── algocite_utilize_dataset_test_fold_{fold}.csv

Source:
    dataset/10-fold_labeled_increasing_relabel_ver3/
    ├── algocite_utilize_dataset_train_fold_{fold}.csv
    ├── algocite_utilize_dataset_val_fold_{fold}.csv
    └── algocite_utilize_dataset_test_fold_{fold}.csv
"""

import os
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

# ── Config ──────────────────────────────────────────────
INPUT_DIR    = './dataset/10-fold_labeled_increasing_relabel_ver3'
OUTPUT_BASE  = './spin-off/dataset'
LABEL_COL    = 'UTILIZE_LABELS'
RANDOM_STATE = 42
PERCENTAGES  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40, 50, 60, 70, 80, 90]
N_FOLDS      = 10
# ────────────────────────────────────────────────────────

sampler = StratifiedShuffleSplit(n_splits=1, test_size=0.01, random_state=RANDOM_STATE)

for fold in range(1, N_FOLDS + 1):

    print(f"\n{'='*55}")
    print(f"FOLD {fold}")
    print(f"{'='*55}")

    # Load base fold files
    train_df = pd.read_csv(f'{INPUT_DIR}/algocite_utilize_dataset_train_fold_{fold}.csv')
    val_df   = pd.read_csv(f'{INPUT_DIR}/algocite_utilize_dataset_val_fold_{fold}.csv')
    test_df  = pd.read_csv(f'{INPUT_DIR}/algocite_utilize_dataset_test_fold_{fold}.csv')

    # Get shuffled stratified indices for each split (same as paper)
    for train_index, _ in sampler.split(train_df, train_df[LABEL_COL]):
        pass
    for val_index, _ in sampler.split(val_df, val_df[LABEL_COL]):
        pass
    for test_index, _ in sampler.split(test_df, test_df[LABEL_COL]):
        pass

    for percent in PERCENTAGES:
        ratio = percent / 100.0

        # Sequential slice — smaller % is always subset of larger %
        train_sub = train_df.iloc[train_index[:int(len(train_index) * ratio)]]
        val_sub   = val_df.iloc[val_index[:int(len(val_index) * ratio)]]
        test_sub  = test_df.iloc[test_index[:int(len(test_index) * ratio)]]

        # Exact path the finetuning notebook expects
        out_dir = f'{OUTPUT_BASE}/fold_{fold}/10-fold_original_{percent}_percent'
        os.makedirs(out_dir, exist_ok=True)

        train_sub.to_csv(f'{out_dir}/algocite_utilize_dataset_train_fold_{fold}.csv', index=False)
        val_sub.to_csv(  f'{out_dir}/algocite_utilize_dataset_val_fold_{fold}.csv',   index=False)
        test_sub.to_csv( f'{out_dir}/algocite_utilize_dataset_test_fold_{fold}.csv',  index=False)

        tl = train_sub[LABEL_COL].value_counts()
        print(f'  [{percent:>2}%] '
              f'train={len(train_sub):>4} '
              f'(UTILIZE={tl.get("UTILIZE",0):>3}, '
              f'NOTUTILIZE={tl.get("NOTUTILIZE",0):>3}) | '
              f'val={len(val_sub):>3} | '
              f'test={len(test_sub):>3}')

print('\n' + '='*55)
print('Done! Final structure:')
print('='*55)
for fold in range(1, N_FOLDS + 1):
    for percent in PERCENTAGES:
        path = f'{OUTPUT_BASE}/fold_{fold}/10-fold_original_{percent}_percent'
        files = os.listdir(path)
        print(f'  fold_{fold}/10-fold_original_{percent}_percent/ → {len(files)} CSVs')

=======================================================
FOLD 1
=======================================================
  [ 1%] train=  25 (UTILIZE=  5, NOTUTILIZE= 20) | val=  6 | test=  3
  [ 2%] train=  51 (UTILIZE= 11, NOTUTILIZE= 40) | val= 12 | test=  7
  [ 3%] train=  76 (UTILIZE= 15, NOTUTILIZE= 61) | val= 19 | test= 10
  [ 4%] train= 102 (UTILIZE= 16, NOTUTILIZE= 86) | val= 25 | test= 14
  [ 5%] train= 127 (UTILIZE= 20, NOTUTILIZE=107) | val= 32 | test= 17
  [ 6%] train= 153 (UTILIZE= 25, NOTUTILIZE=128) | val= 38 | test= 21
  [ 7%] train= 179 (UTILIZE= 30, NOTUTILIZE=149) | val= 44 | test= 24
  [ 8%] train= 204 (UTILIZE= 36, NOTUTILIZE=168) | val= 51 | test= 28
  [ 9%] train= 230 (UTILIZE= 40, NOTUTILIZE=190) | val= 57 | test= 32
  [10%] train= 255 (UTILIZE= 44, NOTUTILIZE=211) | val= 64 | test= 35
  [20%] train= 511 (UTILIZE=110, NOTUTILIZE=401) | val=128 | test= 71
  [30%] train= 767 (UTILIZE=175, NOTUTILIZE=592) | val=192 | test=106
  [40%] train=1023 (UTILIZE=223, NOTUTILIZE=800) | val=256 | test=142
  [50%] train=1279 (UTILIZE=285, NOTUTILIZE=994) | val=320 | test=178
  [60%] train=1535 (UTILIZE=341, NOTUTILIZE=1194) | val=384 | test=213
  [70%] train=1791 (UTILIZE=418, NOTUTILIZE=1373) | val=448 | test=249
  [80%] train=2047 (UTILIZE=484, NOTUTILIZE=1563) | val=512 | test=284
  [90%] train=2303 (UTILIZE=544, NOTUTILIZE=1759) | val=576 | test=320

=======================================================
FOLD 2
=======================================================
  [ 1%] train=  25 (UTILIZE=  5, NOTUTILIZE= 20) | val=  6 | test=  3
  [ 2%] train=  51 (UTILIZE= 11, NOTUTILIZE= 40) | val= 12 | test=  7
  [ 3%] train=  76 (UTILIZE= 15, NOTUTILIZE= 61) | val= 19 | test= 10
  [ 4%] train= 102 (UTILIZE= 16, NOTUTILIZE= 86) | val= 25 | test= 14
  [ 5%] train= 127 (UTILIZE= 20, NOTUTILIZE=107) | val= 32 | test= 17
  [ 6%] train= 153 (UTILIZE= 25, NOTUTILIZE=128) | val= 38 | test= 21
  [ 7%] train= 179 (UTILIZE= 30, NOTUTILIZE=149) | val= 44 | test= 24
  [ 8%] train= 204 (UTILIZE= 36, NOTUTILIZE=168) | val= 51 | test= 28
  [ 9%] train= 230 (UTILIZE= 40, NOTUTILIZE=190) | val= 57 | test= 32
  [10%] train= 255 (UTILIZE= 44, NOTUTILIZE=211) | val= 64 | test= 35
  [20%] train= 511 (UTILIZE=110, NOTUTILIZE=401) | val=128 | test= 71
  [30%] train= 767 (UTILIZE=175, NOTUTILIZE=592) | val=192 | test=106
  [40%] train=1023 (UTILIZE=223, NOTUTILIZE=800) | val=256 | test=142
  [50%] train=1279 (UTILIZE=285, NOTUTILIZE=994) | val=320 | test=178
  [60%] train=1535 (UTILIZE=341, NOTUTILIZE=1194) | val=384 | test=213
  [70%] train=1791 (UTILIZE=418, NOTUTILIZE=1373) | val=448 | test=249
  [80%] train=2047 (UTILIZE=484, NOTUTILIZE=1563) | val=512 | test=284
  [90%] train=2303 (UTILIZE=544, NOTUTILIZE=1759) | val=576 | test=320

=======================================================
FOLD 3
=======================================================
  [ 1%] train=  25 (UTILIZE=  5, NOTUTILIZE= 20) | val=  6 | test=  3
  [ 2%] train=  51 (UTILIZE= 12, NOTUTILIZE= 39) | val= 12 | test=  7
  [ 3%] train=  76 (UTILIZE= 15, NOTUTILIZE= 61) | val= 19 | test= 10
  [ 4%] train= 102 (UTILIZE= 19, NOTUTILIZE= 83) | val= 25 | test= 14
  [ 5%] train= 128 (UTILIZE= 25, NOTUTILIZE=103) | val= 32 | test= 17
  [ 6%] train= 153 (UTILIZE= 32, NOTUTILIZE=121) | val= 38 | test= 21
  [ 7%] train= 179 (UTILIZE= 39, NOTUTILIZE=140) | val= 44 | test= 24
  [ 8%] train= 204 (UTILIZE= 44, NOTUTILIZE=160) | val= 51 | test= 28
  [ 9%] train= 230 (UTILIZE= 48, NOTUTILIZE=182) | val= 57 | test= 31
  [10%] train= 256 (UTILIZE= 54, NOTUTILIZE=202) | val= 64 | test= 35
  [20%] train= 512 (UTILIZE=113, NOTUTILIZE=399) | val=128 | test= 71
  [30%] train= 768 (UTILIZE=175, NOTUTILIZE=593) | val=192 | test=106
  [40%] train=1024 (UTILIZE=233, NOTUTILIZE=791) | val=256 | test=142
  [50%] train=1280 (UTILIZE=280, NOTUTILIZE=1000) | val=320 | test=177
  [60%] train=1536 (UTILIZE=345, NOTUTILIZE=1191) | val=384 | test=213
  [70%] train=1792 (UTILIZE=418, NOTUTILIZE=1374) | val=448 | test=248
  [80%] train=2048 (UTILIZE=484, NOTUTILIZE=1564) | val=512 | test=284
  [90%] train=2304 (UTILIZE=545, NOTUTILIZE=1759) | val=576 | test=319

=======================================================
FOLD 4
=======================================================
  [ 1%] train=  25 (UTILIZE=  5, NOTUTILIZE= 20) | val=  6 | test=  3
  [ 2%] train=  51 (UTILIZE= 12, NOTUTILIZE= 39) | val= 12 | test=  7
  [ 3%] train=  76 (UTILIZE= 15, NOTUTILIZE= 61) | val= 19 | test= 10
  [ 4%] train= 102 (UTILIZE= 19, NOTUTILIZE= 83) | val= 25 | test= 14
  [ 5%] train= 128 (UTILIZE= 25, NOTUTILIZE=103) | val= 32 | test= 17
  [ 6%] train= 153 (UTILIZE= 32, NOTUTILIZE=121) | val= 38 | test= 21
  [ 7%] train= 179 (UTILIZE= 39, NOTUTILIZE=140) | val= 44 | test= 24
  [ 8%] train= 204 (UTILIZE= 44, NOTUTILIZE=160) | val= 51 | test= 28
  [ 9%] train= 230 (UTILIZE= 48, NOTUTILIZE=182) | val= 57 | test= 31
  [10%] train= 256 (UTILIZE= 54, NOTUTILIZE=202) | val= 64 | test= 35
  [20%] train= 512 (UTILIZE=113, NOTUTILIZE=399) | val=128 | test= 71
  [30%] train= 768 (UTILIZE=175, NOTUTILIZE=593) | val=192 | test=106
  [40%] train=1024 (UTILIZE=233, NOTUTILIZE=791) | val=256 | test=142
  [50%] train=1280 (UTILIZE=280, NOTUTILIZE=1000) | val=320 | test=177
  [60%] train=1536 (UTILIZE=345, NOTUTILIZE=1191) | val=384 | test=213
  [70%] train=1792 (UTILIZE=418, NOTUTILIZE=1374) | val=448 | test=248
  [80%] train=2048 (UTILIZE=484, NOTUTILIZE=1564) | val=512 | test=284
  [90%] train=2304 (UTILIZE=545, NOTUTILIZE=1759) | val=576 | test=319

=======================================================
FOLD 5
=======================================================
  [ 1%] train=  25 (UTILIZE=  5, NOTUTILIZE= 20) | val=  6 | test=  3
  [ 2%] train=  51 (UTILIZE= 12, NOTUTILIZE= 39) | val= 12 | test=  7
  [ 3%] train=  76 (UTILIZE= 15, NOTUTILIZE= 61) | val= 19 | test= 10
  [ 4%] train= 102 (UTILIZE= 19, NOTUTILIZE= 83) | val= 25 | test= 14
  [ 5%] train= 128 (UTILIZE= 25, NOTUTILIZE=103) | val= 32 | test= 17
  [ 6%] train= 153 (UTILIZE= 32, NOTUTILIZE=121) | val= 38 | test= 21
  [ 7%] train= 179 (UTILIZE= 39, NOTUTILIZE=140) | val= 44 | test= 24
  [ 8%] train= 204 (UTILIZE= 44, NOTUTILIZE=160) | val= 51 | test= 28
  [ 9%] train= 230 (UTILIZE= 48, NOTUTILIZE=182) | val= 57 | test= 31
  [10%] train= 256 (UTILIZE= 54, NOTUTILIZE=202) | val= 64 | test= 35
  [20%] train= 512 (UTILIZE=113, NOTUTILIZE=399) | val=128 | test= 71
  [30%] train= 768 (UTILIZE=175, NOTUTILIZE=593) | val=192 | test=106
  [40%] train=1024 (UTILIZE=233, NOTUTILIZE=791) | val=256 | test=142
  [50%] train=1280 (UTILIZE=280, NOTUTILIZE=1000) | val=320 | test=177
  [60%] train=1536 (UTILIZE=345, NOTUTILIZE=1191) | val=384 | test=213
  [70%] train=1792 (UTILIZE=418, NOTUTILIZE=1374) | val=448 | test=248
  [80%] train=2048 (UTILIZE=484, NOTUTILIZE=1564) | val=512 | test=284
  [90%] train=2304 (UTILIZE=545, NOTUTILIZE=1759) | val=576 | test=319

=======================================================
FOLD 6
=======================================================
  [ 1%] train=  25 (UTILIZE=  5, NOTUTILIZE= 20) | val=  6 | test=  3
  [ 2%] train=  51 (UTILIZE= 12, NOTUTILIZE= 39) | val= 12 | test=  7
  [ 3%] train=  76 (UTILIZE= 15, NOTUTILIZE= 61) | val= 19 | test= 10
  [ 4%] train= 102 (UTILIZE= 19, NOTUTILIZE= 83) | val= 25 | test= 14
  [ 5%] train= 128 (UTILIZE= 25, NOTUTILIZE=103) | val= 32 | test= 17
  [ 6%] train= 153 (UTILIZE= 32, NOTUTILIZE=121) | val= 38 | test= 21
  [ 7%] train= 179 (UTILIZE= 39, NOTUTILIZE=140) | val= 44 | test= 24
  [ 8%] train= 204 (UTILIZE= 44, NOTUTILIZE=160) | val= 51 | test= 28
  [ 9%] train= 230 (UTILIZE= 48, NOTUTILIZE=182) | val= 57 | test= 31
  [10%] train= 256 (UTILIZE= 54, NOTUTILIZE=202) | val= 64 | test= 35
  [20%] train= 512 (UTILIZE=113, NOTUTILIZE=399) | val=128 | test= 71
  [30%] train= 768 (UTILIZE=175, NOTUTILIZE=593) | val=192 | test=106
  [40%] train=1024 (UTILIZE=233, NOTUTILIZE=791) | val=256 | test=142
  [50%] train=1280 (UTILIZE=280, NOTUTILIZE=1000) | val=320 | test=177
  [60%] train=1536 (UTILIZE=345, NOTUTILIZE=1191) | val=384 | test=213
  [70%] train=1792 (UTILIZE=418, NOTUTILIZE=1374) | val=448 | test=248
  [80%] train=2048 (UTILIZE=484, NOTUTILIZE=1564) | val=512 | test=284
  [90%] train=2304 (UTILIZE=545, NOTUTILIZE=1759) | val=576 | test=319

=======================================================
FOLD 7
=======================================================
  [ 1%] train=  25 (UTILIZE=  5, NOTUTILIZE= 20) | val=  6 | test=  3
  [ 2%] train=  51 (UTILIZE= 12, NOTUTILIZE= 39) | val= 12 | test=  7
  [ 3%] train=  76 (UTILIZE= 15, NOTUTILIZE= 61) | val= 19 | test= 10
  [ 4%] train= 102 (UTILIZE= 19, NOTUTILIZE= 83) | val= 25 | test= 14
  [ 5%] train= 128 (UTILIZE= 25, NOTUTILIZE=103) | val= 32 | test= 17
  [ 6%] train= 153 (UTILIZE= 32, NOTUTILIZE=121) | val= 38 | test= 21
  [ 7%] train= 179 (UTILIZE= 39, NOTUTILIZE=140) | val= 44 | test= 24
  [ 8%] train= 204 (UTILIZE= 44, NOTUTILIZE=160) | val= 51 | test= 28
  [ 9%] train= 230 (UTILIZE= 48, NOTUTILIZE=182) | val= 57 | test= 31
  [10%] train= 256 (UTILIZE= 54, NOTUTILIZE=202) | val= 64 | test= 35
  [20%] train= 512 (UTILIZE=113, NOTUTILIZE=399) | val=128 | test= 71
  [30%] train= 768 (UTILIZE=175, NOTUTILIZE=593) | val=192 | test=106
  [40%] train=1024 (UTILIZE=233, NOTUTILIZE=791) | val=256 | test=142
  [50%] train=1280 (UTILIZE=280, NOTUTILIZE=1000) | val=320 | test=177
  [60%] train=1536 (UTILIZE=345, NOTUTILIZE=1191) | val=384 | test=213
  [70%] train=1792 (UTILIZE=418, NOTUTILIZE=1374) | val=448 | test=248
  [80%] train=2048 (UTILIZE=484, NOTUTILIZE=1564) | val=512 | test=284
  [90%] train=2304 (UTILIZE=545, NOTUTILIZE=1759) | val=576 | test=319

=======================================================
FOLD 8
=======================================================
  [ 1%] train=  25 (UTILIZE=  5, NOTUTILIZE= 20) | val=  6 | test=  3
  [ 2%] train=  51 (UTILIZE= 12, NOTUTILIZE= 39) | val= 12 | test=  7
  [ 3%] train=  76 (UTILIZE= 15, NOTUTILIZE= 61) | val= 19 | test= 10
  [ 4%] train= 102 (UTILIZE= 19, NOTUTILIZE= 83) | val= 25 | test= 14
  [ 5%] train= 128 (UTILIZE= 25, NOTUTILIZE=103) | val= 32 | test= 17
  [ 6%] train= 153 (UTILIZE= 32, NOTUTILIZE=121) | val= 38 | test= 21
  [ 7%] train= 179 (UTILIZE= 39, NOTUTILIZE=140) | val= 44 | test= 24
  [ 8%] train= 204 (UTILIZE= 44, NOTUTILIZE=160) | val= 51 | test= 28
  [ 9%] train= 230 (UTILIZE= 48, NOTUTILIZE=182) | val= 57 | test= 31
  [10%] train= 256 (UTILIZE= 54, NOTUTILIZE=202) | val= 64 | test= 35
  [20%] train= 512 (UTILIZE=113, NOTUTILIZE=399) | val=128 | test= 71
  [30%] train= 768 (UTILIZE=175, NOTUTILIZE=593) | val=192 | test=106
  [40%] train=1024 (UTILIZE=233, NOTUTILIZE=791) | val=256 | test=142
  [50%] train=1280 (UTILIZE=280, NOTUTILIZE=1000) | val=320 | test=177
  [60%] train=1536 (UTILIZE=345, NOTUTILIZE=1191) | val=384 | test=213
  [70%] train=1792 (UTILIZE=418, NOTUTILIZE=1374) | val=448 | test=248
  [80%] train=2048 (UTILIZE=484, NOTUTILIZE=1564) | val=512 | test=284
  [90%] train=2304 (UTILIZE=545, NOTUTILIZE=1759) | val=576 | test=319

=======================================================
FOLD 9
=======================================================
  [ 1%] train=  25 (UTILIZE=  5, NOTUTILIZE= 20) | val=  6 | test=  3
  [ 2%] train=  51 (UTILIZE= 12, NOTUTILIZE= 39) | val= 12 | test=  7
  [ 3%] train=  76 (UTILIZE= 15, NOTUTILIZE= 61) | val= 19 | test= 10
  [ 4%] train= 102 (UTILIZE= 19, NOTUTILIZE= 83) | val= 25 | test= 14
  [ 5%] train= 128 (UTILIZE= 25, NOTUTILIZE=103) | val= 32 | test= 17
  [ 6%] train= 153 (UTILIZE= 32, NOTUTILIZE=121) | val= 38 | test= 21
  [ 7%] train= 179 (UTILIZE= 39, NOTUTILIZE=140) | val= 44 | test= 24
  [ 8%] train= 204 (UTILIZE= 44, NOTUTILIZE=160) | val= 51 | test= 28
  [ 9%] train= 230 (UTILIZE= 48, NOTUTILIZE=182) | val= 57 | test= 31
  [10%] train= 256 (UTILIZE= 54, NOTUTILIZE=202) | val= 64 | test= 35
  [20%] train= 512 (UTILIZE=113, NOTUTILIZE=399) | val=128 | test= 71
  [30%] train= 768 (UTILIZE=175, NOTUTILIZE=593) | val=192 | test=106
  [40%] train=1024 (UTILIZE=233, NOTUTILIZE=791) | val=256 | test=142
  [50%] train=1280 (UTILIZE=280, NOTUTILIZE=1000) | val=320 | test=177
  [60%] train=1536 (UTILIZE=345, NOTUTILIZE=1191) | val=384 | test=213
  [70%] train=1792 (UTILIZE=418, NOTUTILIZE=1374) | val=448 | test=248
  [80%] train=2048 (UTILIZE=484, NOTUTILIZE=1564) | val=512 | test=284
  [90%] train=2304 (UTILIZE=545, NOTUTILIZE=1759) | val=576 | test=319

=======================================================
FOLD 10
=======================================================
  [ 1%] train=  25 (UTILIZE=  5, NOTUTILIZE= 20) | val=  6 | test=  3
  [ 2%] train=  51 (UTILIZE= 12, NOTUTILIZE= 39) | val= 12 | test=  7
  [ 3%] train=  76 (UTILIZE= 15, NOTUTILIZE= 61) | val= 19 | test= 10
  [ 4%] train= 102 (UTILIZE= 19, NOTUTILIZE= 83) | val= 25 | test= 14
  [ 5%] train= 128 (UTILIZE= 25, NOTUTILIZE=103) | val= 32 | test= 17
  [ 6%] train= 153 (UTILIZE= 32, NOTUTILIZE=121) | val= 38 | test= 21
  [ 7%] train= 179 (UTILIZE= 39, NOTUTILIZE=140) | val= 44 | test= 24
  [ 8%] train= 204 (UTILIZE= 44, NOTUTILIZE=160) | val= 51 | test= 28
  [ 9%] train= 230 (UTILIZE= 48, NOTUTILIZE=182) | val= 57 | test= 31
  [10%] train= 256 (UTILIZE= 54, NOTUTILIZE=202) | val= 64 | test= 35
  [20%] train= 512 (UTILIZE=113, NOTUTILIZE=399) | val=128 | test= 71
  [30%] train= 768 (UTILIZE=175, NOTUTILIZE=593) | val=192 | test=106
  [40%] train=1024 (UTILIZE=233, NOTUTILIZE=791) | val=256 | test=142
  [50%] train=1280 (UTILIZE=280, NOTUTILIZE=1000) | val=320 | test=177
  [60%] train=1536 (UTILIZE=345, NOTUTILIZE=1191) | val=384 | test=213
  [70%] train=1792 (UTILIZE=418, NOTUTILIZE=1374) | val=448 | test=248
  [80%] train=2048 (UTILIZE=484, NOTUTILIZE=1564) | val=512 | test=284
  [90%] train=2304 (UTILIZE=545, NOTUTILIZE=1759) | val=576 | test=319

=======================================================
Done! Final structure:
=======================================================
  fold_1/10-fold_original_1_percent/ → 3 CSVs
  fold_1/10-fold_original_2_percent/ → 3 CSVs
  fold_1/10-fold_original_3_percent/ → 3 CSVs
  fold_1/10-fold_original_4_percent/ → 3 CSVs
  fold_1/10-fold_original_5_percent/ → 3 CSVs
  fold_1/10-fold_original_6_percent/ → 3 CSVs
  fold_1/10-fold_original_7_percent/ → 3 CSVs
  fold_1/10-fold_original_8_percent/ → 3 CSVs
  fold_1/10-fold_original_9_percent/ → 3 CSVs
  fold_1/10-fold_original_10_percent/ → 3 CSVs
  fold_1/10-fold_original_20_percent/ → 3 CSVs
  fold_1/10-fold_original_30_percent/ → 3 CSVs
  fold_1/10-fold_original_40_percent/ → 3 CSVs
  fold_1/10-fold_original_50_percent/ → 3 CSVs
  fold_1/10-fold_original_60_percent/ → 3 CSVs
  fold_1/10-fold_original_70_percent/ → 3 CSVs
  fold_1/10-fold_original_80_percent/ → 3 CSVs
  fold_1/10-fold_original_90_percent/ → 3 CSVs
  fold_2/10-fold_original_1_percent/ → 3 CSVs
  fold_2/10-fold_original_2_percent/ → 3 CSVs
  fold_2/10-fold_original_3_percent/ → 3 CSVs
  fold_2/10-fold_original_4_percent/ → 3 CSVs
  fold_2/10-fold_original_5_percent/ → 3 CSVs
  fold_2/10-fold_original_6_percent/ → 3 CSVs
  fold_2/10-fold_original_7_percent/ → 3 CSVs
  fold_2/10-fold_original_8_percent/ → 3 CSVs
  fold_2/10-fold_original_9_percent/ → 3 CSVs
  fold_2/10-fold_original_10_percent/ → 3 CSVs
  fold_2/10-fold_original_20_percent/ → 3 CSVs
  fold_2/10-fold_original_30_percent/ → 3 CSVs
  fold_2/10-fold_original_40_percent/ → 3 CSVs
  fold_2/10-fold_original_50_percent/ → 3 CSVs
  fold_2/10-fold_original_60_percent/ → 3 CSVs
  fold_2/10-fold_original_70_percent/ → 3 CSVs
  fold_2/10-fold_original_80_percent/ → 3 CSVs
  fold_2/10-fold_original_90_percent/ → 3 CSVs
  fold_3/10-fold_original_1_percent/ → 3 CSVs
  fold_3/10-fold_original_2_percent/ → 3 CSVs
  fold_3/10-fold_original_3_percent/ → 3 CSVs
  fold_3/10-fold_original_4_percent/ → 3 CSVs
  fold_3/10-fold_original_5_percent/ → 3 CSVs
  fold_3/10-fold_original_6_percent/ → 3 CSVs
  fold_3/10-fold_original_7_percent/ → 3 CSVs
  fold_3/10-fold_original_8_percent/ → 3 CSVs
  fold_3/10-fold_original_9_percent/ → 3 CSVs
  fold_3/10-fold_original_10_percent/ → 3 CSVs
  fold_3/10-fold_original_20_percent/ → 3 CSVs
  fold_3/10-fold_original_30_percent/ → 3 CSVs
  fold_3/10-fold_original_40_percent/ → 3 CSVs
  fold_3/10-fold_original_50_percent/ → 3 CSVs
  fold_3/10-fold_original_60_percent/ → 3 CSVs
  fold_3/10-fold_original_70_percent/ → 3 CSVs
  fold_3/10-fold_original_80_percent/ → 3 CSVs
  fold_3/10-fold_original_90_percent/ → 3 CSVs
  fold_4/10-fold_original_1_percent/ → 3 CSVs
  fold_4/10-fold_original_2_percent/ → 3 CSVs
  fold_4/10-fold_original_3_percent/ → 3 CSVs
  fold_4/10-fold_original_4_percent/ → 3 CSVs
  fold_4/10-fold_original_5_percent/ → 3 CSVs
  fold_4/10-fold_original_6_percent/ → 3 CSVs
  fold_4/10-fold_original_7_percent/ → 3 CSVs
  fold_4/10-fold_original_8_percent/ → 3 CSVs
  fold_4/10-fold_original_9_percent/ → 3 CSVs
  fold_4/10-fold_original_10_percent/ → 3 CSVs
  fold_4/10-fold_original_20_percent/ → 3 CSVs
  fold_4/10-fold_original_30_percent/ → 3 CSVs
  fold_4/10-fold_original_40_percent/ → 3 CSVs
  fold_4/10-fold_original_50_percent/ → 3 CSVs
  fold_4/10-fold_original_60_percent/ → 3 CSVs
  fold_4/10-fold_original_70_percent/ → 3 CSVs
  fold_4/10-fold_original_80_percent/ → 3 CSVs
  fold_4/10-fold_original_90_percent/ → 3 CSVs
  fold_5/10-fold_original_1_percent/ → 3 CSVs
  fold_5/10-fold_original_2_percent/ → 3 CSVs
  fold_5/10-fold_original_3_percent/ → 3 CSVs
  fold_5/10-fold_original_4_percent/ → 3 CSVs
  fold_5/10-fold_original_5_percent/ → 3 CSVs
  fold_5/10-fold_original_6_percent/ → 3 CSVs
  fold_5/10-fold_original_7_percent/ → 3 CSVs
  fold_5/10-fold_original_8_percent/ → 3 CSVs
  fold_5/10-fold_original_9_percent/ → 3 CSVs
  fold_5/10-fold_original_10_percent/ → 3 CSVs
  fold_5/10-fold_original_20_percent/ → 3 CSVs
  fold_5/10-fold_original_30_percent/ → 3 CSVs
  fold_5/10-fold_original_40_percent/ → 3 CSVs
  fold_5/10-fold_original_50_percent/ → 3 CSVs
  fold_5/10-fold_original_60_percent/ → 3 CSVs
  fold_5/10-fold_original_70_percent/ → 3 CSVs
  fold_5/10-fold_original_80_percent/ → 3 CSVs
  fold_5/10-fold_original_90_percent/ → 3 CSVs
  fold_6/10-fold_original_1_percent/ → 3 CSVs
  fold_6/10-fold_original_2_percent/ → 3 CSVs
  fold_6/10-fold_original_3_percent/ → 3 CSVs
  fold_6/10-fold_original_4_percent/ → 3 CSVs
  fold_6/10-fold_original_5_percent/ → 3 CSVs
  fold_6/10-fold_original_6_percent/ → 3 CSVs
  fold_6/10-fold_original_7_percent/ → 3 CSVs
  fold_6/10-fold_original_8_percent/ → 3 CSVs
  fold_6/10-fold_original_9_percent/ → 3 CSVs
  fold_6/10-fold_original_10_percent/ → 3 CSVs
  fold_6/10-fold_original_20_percent/ → 3 CSVs
  fold_6/10-fold_original_30_percent/ → 3 CSVs
  fold_6/10-fold_original_40_percent/ → 3 CSVs
  fold_6/10-fold_original_50_percent/ → 3 CSVs
  fold_6/10-fold_original_60_percent/ → 3 CSVs
  fold_6/10-fold_original_70_percent/ → 3 CSVs
  fold_6/10-fold_original_80_percent/ → 3 CSVs
  fold_6/10-fold_original_90_percent/ → 3 CSVs
  fold_7/10-fold_original_1_percent/ → 3 CSVs
  fold_7/10-fold_original_2_percent/ → 3 CSVs
  fold_7/10-fold_original_3_percent/ → 3 CSVs
  fold_7/10-fold_original_4_percent/ → 3 CSVs
  fold_7/10-fold_original_5_percent/ → 3 CSVs
  fold_7/10-fold_original_6_percent/ → 3 CSVs
  fold_7/10-fold_original_7_percent/ → 3 CSVs
  fold_7/10-fold_original_8_percent/ → 3 CSVs
  fold_7/10-fold_original_9_percent/ → 3 CSVs
  fold_7/10-fold_original_10_percent/ → 3 CSVs
  fold_7/10-fold_original_20_percent/ → 3 CSVs
  fold_7/10-fold_original_30_percent/ → 3 CSVs
  fold_7/10-fold_original_40_percent/ → 3 CSVs
  fold_7/10-fold_original_50_percent/ → 3 CSVs
  fold_7/10-fold_original_60_percent/ → 3 CSVs
  fold_7/10-fold_original_70_percent/ → 3 CSVs
  fold_7/10-fold_original_80_percent/ → 3 CSVs
  fold_7/10-fold_original_90_percent/ → 3 CSVs
  fold_8/10-fold_original_1_percent/ → 3 CSVs
  fold_8/10-fold_original_2_percent/ → 3 CSVs
  fold_8/10-fold_original_3_percent/ → 3 CSVs

In [1]:
import os
import pandas as pd
from sklearn.model_selection import StratifiedKFold, train_test_split

TRAIN_PATH   = "processed_data/final_dataset/df_train_clean.csv"
VAL_PATH     = "processed_data/final_dataset/df_val_clean.csv"
TEST_PATH    = "processed_data/final_dataset/df_test_clean.csv"

OUTPUT_DIR   = "./10_fold_dataset/10-fold_labeled_final/10-fold_labeled_increasing_relabel_ver3"
LABEL_COL    = "UTILIZE_LABELS"
RANDOM_STATE = 42
N_FOLDS      = 10

os.makedirs(OUTPUT_DIR, exist_ok=True)

In [2]:
# Load and combine into one pool
train_df = pd.read_csv(TRAIN_PATH)
val_df   = pd.read_csv(VAL_PATH)
test_df  = pd.read_csv(TEST_PATH)

full_df = pd.concat([train_df, val_df, test_df], axis=0).reset_index(drop=True)
print(f"Total pool: {len(full_df)} rows")
print(full_df[LABEL_COL].value_counts())

Total pool: 8931 rows
UTILIZE_LABELS
NOTUTILIZE    6640
UTILIZE       2291
Name: count, dtype: int64

In [3]:
# Create 10 stratified folds
skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_STATE)
X   = full_df.index.values
y   = full_df[LABEL_COL].values

In [4]:
for fold_num, (train_val_idx, test_idx) in enumerate(skf.split(X, y), start=1):

    # Split train_val → train 80% / val 20%
    train_idx, val_idx = train_test_split(
        train_val_idx,
        test_size = 0.2,
        random_state = RANDOM_STATE,
        stratify = y[train_val_idx]
    )

    full_df.iloc[train_idx].reset_index(drop=True).to_csv(
        f"{OUTPUT_DIR}/algocite_utilize_dataset_train_fold_{fold_num}.csv", index=False)
    full_df.iloc[val_idx].reset_index(drop=True).to_csv(
        f"{OUTPUT_DIR}/algocite_utilize_dataset_val_fold_{fold_num}.csv", index=False)
    full_df.iloc[test_idx].reset_index(drop=True).to_csv(
        f"{OUTPUT_DIR}/algocite_utilize_dataset_test_fold_{fold_num}.csv", index=False)

    print(f"Fold {fold_num}: train={len(train_idx)}, val={len(val_idx)}, test={len(test_idx)}")

print("\nDone! Files saved to:", OUTPUT_DIR)

Fold 1: train=6429, val=1608, test=894
Fold 2: train=6430, val=1608, test=893
Fold 3: train=6430, val=1608, test=893
Fold 4: train=6430, val=1608, test=893
Fold 5: train=6430, val=1608, test=893
Fold 6: train=6430, val=1608, test=893
Fold 7: train=6430, val=1608, test=893
Fold 8: train=6430, val=1608, test=893
Fold 9: train=6430, val=1608, test=893
Fold 10: train=6430, val=1608, test=893

Done! Files saved to: ./10_fold_dataset/10-fold_labeled_final/10-fold_labeled_increasing_relabel_ver3

In [5]:
# Import required libraries
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

# Load train, test, and val dataframes
fold = 1

train_df = pd.read_csv(f'./10_fold_dataset/10-fold_labeled_final/10-fold_labeled_increasing_relabel_ver3/algocite_utilize_dataset_train_fold_{fold}.csv')
val_df = pd.read_csv(f'./10_fold_dataset/10-fold_labeled_final/10-fold_labeled_increasing_relabel_ver3/algocite_utilize_dataset_val_fold_{fold}.csv')
test_df = pd.read_csv(f'./10_fold_dataset/10-fold_labeled_final/10-fold_labeled_increasing_relabel_ver3/algocite_utilize_dataset_test_fold_{fold}.csv')

# Define the column name containing the labels for stratified sampling
label_col = 'UTILIZE_LABELS'

# Create a stratified sampler with the desired percentages
sampler = StratifiedShuffleSplit(n_splits=1, test_size=0.01, random_state=42)

# Split the train dataframe into stratified samples
for train_index, _ in sampler.split(train_df, train_df[label_col]):
    train_1percent_df = train_df.iloc[train_index[:int(len(train_index)*0.01)]]
    train_2percent_df = train_df.iloc[train_index[:int(len(train_index)*0.02)]]
    train_3percent_df = train_df.iloc[train_index[:int(len(train_index)*0.03)]]
    train_4percent_df = train_df.iloc[train_index[:int(len(train_index)*0.04)]]
    train_5percent_df = train_df.iloc[train_index[:int(len(train_index)*0.05)]]
    train_7percent_df = train_df.iloc[train_index[:int(len(train_index)*0.07)]]
    train_10percent_df = train_df.iloc[train_index[:int(len(train_index)*0.1)]]
    train_20percent_df = train_df.iloc[train_index[:int(len(train_index)*0.2)]]
    train_30percent_df = train_df.iloc[train_index[:int(len(train_index)*0.3)]]
    train_40percent_df = train_df.iloc[train_index[:int(len(train_index)*0.4)]]
    train_50percent_df = train_df.iloc[train_index[:int(len(train_index)*0.5)]]
    train_70percent_df = train_df.iloc[train_index[:int(len(train_index)*0.7)]]

# Split the test dataframe into stratified samples
for test_index, _ in sampler.split(test_df, test_df[label_col]):
    test_1percent_df = test_df.iloc[test_index[:int(len(test_index)*0.01)]]
    test_2percent_df = test_df.iloc[test_index[:int(len(test_index)*0.02)]]
    test_3percent_df = test_df.iloc[test_index[:int(len(test_index)*0.03)]]
    test_4percent_df = test_df.iloc[test_index[:int(len(test_index)*0.04)]]
    test_5percent_df = test_df.iloc[test_index[:int(len(test_index)*0.05)]]
    test_7percent_df = test_df.iloc[test_index[:int(len(test_index)*0.07)]]
    test_10percent_df = test_df.iloc[test_index[:int(len(test_index)*0.1)]]
    test_20percent_df = test_df.iloc[test_index[:int(len(test_index)*0.2)]]
    test_30percent_df = test_df.iloc[test_index[:int(len(test_index)*0.3)]]
    test_40percent_df = test_df.iloc[test_index[:int(len(test_index)*0.4)]]
    test_50percent_df = test_df.iloc[test_index[:int(len(test_index)*0.5)]]
    test_70percent_df = test_df.iloc[test_index[:int(len(test_index)*0.7)]]

# Split the validation dataframe into stratified samples
for val_index, _ in sampler.split(val_df, val_df[label_col]):
    val_1percent_df = val_df.iloc[val_index[:int(len(val_index)*0.01)]]
    val_2percent_df = val_df.iloc[val_index[:int(len(val_index)*0.02)]]
    val_3percent_df = val_df.iloc[val_index[:int(len(val_index)*0.03)]]
    val_4percent_df = val_df.iloc[val_index[:int(len(val_index)*0.04)]]
    val_5percent_df = val_df.iloc[val_index[:int(len(val_index)*0.05)]]
    val_7percent_df = val_df.iloc[val_index[:int(len(val_index)*0.07)]]
    val_10percent_df = val_df.iloc[val_index[:int(len(val_index)*0.1)]]
    val_20percent_df = val_df.iloc[val_index[:int(len(val_index)*0.2)]]
    val_30percent_df = val_df.iloc[val_index[:int(len(val_index)*0.3)]]
    val_40percent_df = val_df.iloc[val_index[:int(len(val_index)*0.4)]]
    val_50percent_df = val_df.iloc[val_index[:int(len(val_index)*0.5)]]
    val_70percent_df = val_df.iloc[val_index[:int(len(val_index)*0.7)]]

In [6]:
import os
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

PERCENTAGES  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40, 50, 60, 70, 80, 90]
INPUT_DIR    = './10_fold_dataset/10-fold_labeled_final/10-fold_labeled_increasing_relabel_ver3'
OUTPUT_BASE  = './10_fold_dataset/10-fold_labeled_final'
LABEL_COL    = 'UTILIZE_LABELS'

for fold in range(1, 11):

    train_df = pd.read_csv(f'{INPUT_DIR}/algocite_utilize_dataset_train_fold_{fold}.csv')
    val_df   = pd.read_csv(f'{INPUT_DIR}/algocite_utilize_dataset_val_fold_{fold}.csv')
    test_df  = pd.read_csv(f'{INPUT_DIR}/algocite_utilize_dataset_test_fold_{fold}.csv')

    sampler = StratifiedShuffleSplit(n_splits=1, test_size=0.01, random_state=42)

    # get shuffled indices for each split
    for train_index, _ in sampler.split(train_df, train_df[LABEL_COL]):
        pass
    for val_index, _ in sampler.split(val_df, val_df[LABEL_COL]):
        pass
    for test_index, _ in sampler.split(test_df, test_df[LABEL_COL]):
        pass

    for percent in PERCENTAGES:
        ratio = percent / 100.0

        train_sub = train_df.iloc[train_index[:int(len(train_index) * ratio)]]
        val_sub   = val_df.iloc[val_index[:int(len(val_index) * ratio)]]
        test_sub  = test_df.iloc[test_index[:int(len(test_index) * ratio)]]

        out_dir = f'{OUTPUT_BASE}/10-fold_labeled_increasing_relabel_ver3_{percent}_percent'
        os.makedirs(out_dir, exist_ok=True)

        train_sub.to_csv(f'{out_dir}/algocite_utilize_dataset_train_fold_{fold}.csv', index=False)
        val_sub.to_csv(  f'{out_dir}/algocite_utilize_dataset_val_fold_{fold}.csv',   index=False)
        test_sub.to_csv( f'{out_dir}/algocite_utilize_dataset_test_fold_{fold}.csv',  index=False)

        print(f'Fold {fold} [{percent:>2}%]: '
              f'train={len(train_sub)} | '
              f'val={len(val_sub)} | '
              f'test={len(test_sub)}')

print('\nDone! All folds and percentages saved.')

Fold 1 [ 1%]: train=63 | val=15 | test=8
Fold 1 [ 2%]: train=127 | val=31 | test=17
Fold 1 [ 3%]: train=190 | val=47 | test=26
Fold 1 [ 4%]: train=254 | val=63 | test=35
Fold 1 [ 5%]: train=318 | val=79 | test=44
Fold 1 [ 6%]: train=381 | val=95 | test=53
Fold 1 [ 7%]: train=445 | val=111 | test=61
Fold 1 [ 8%]: train=509 | val=127 | test=70
Fold 1 [ 9%]: train=572 | val=143 | test=79
Fold 1 [10%]: train=636 | val=159 | test=88
Fold 1 [20%]: train=1272 | val=318 | test=177
Fold 1 [30%]: train=1909 | val=477 | test=265
Fold 1 [40%]: train=2545 | val=636 | test=354
Fold 1 [50%]: train=3182 | val=795 | test=442
Fold 1 [60%]: train=3818 | val=954 | test=531
Fold 1 [70%]: train=4454 | val=1113 | test=619
Fold 1 [80%]: train=5091 | val=1272 | test=708
Fold 1 [90%]: train=5727 | val=1431 | test=796
Fold 2 [ 1%]: train=63 | val=15 | test=8
Fold 2 [ 2%]: train=127 | val=31 | test=17
Fold 2 [ 3%]: train=190 | val=47 | test=26
Fold 2 [ 4%]: train=254 | val=63 | test=35
Fold 2 [ 5%]: train=318 | val=79 | test=44
Fold 2 [ 6%]: train=381 | val=95 | test=53
Fold 2 [ 7%]: train=445 | val=111 | test=61
Fold 2 [ 8%]: train=509 | val=127 | test=70
Fold 2 [ 9%]: train=572 | val=143 | test=79
Fold 2 [10%]: train=636 | val=159 | test=88
Fold 2 [20%]: train=1273 | val=318 | test=176
Fold 2 [30%]: train=1909 | val=477 | test=265
Fold 2 [40%]: train=2546 | val=636 | test=353
Fold 2 [50%]: train=3182 | val=795 | test=442
Fold 2 [60%]: train=3819 | val=954 | test=530
Fold 2 [70%]: train=4455 | val=1113 | test=618
Fold 2 [80%]: train=5092 | val=1272 | test=707
Fold 2 [90%]: train=5728 | val=1431 | test=795
Fold 3 [ 1%]: train=63 | val=15 | test=8
Fold 3 [ 2%]: train=127 | val=31 | test=17
Fold 3 [ 3%]: train=190 | val=47 | test=26
Fold 3 [ 4%]: train=254 | val=63 | test=35
Fold 3 [ 5%]: train=318 | val=79 | test=44
Fold 3 [ 6%]: train=381 | val=95 | test=53
Fold 3 [ 7%]: train=445 | val=111 | test=61
Fold 3 [ 8%]: train=509 | val=127 | test=70
Fold 3 [ 9%]: train=572 | val=143 | test=79
Fold 3 [10%]: train=636 | val=159 | test=88
Fold 3 [20%]: train=1273 | val=318 | test=176
Fold 3 [30%]: train=1909 | val=477 | test=265
Fold 3 [40%]: train=2546 | val=636 | test=353
Fold 3 [50%]: train=3182 | val=795 | test=442
Fold 3 [60%]: train=3819 | val=954 | test=530
Fold 3 [70%]: train=4455 | val=1113 | test=618
Fold 3 [80%]: train=5092 | val=1272 | test=707
Fold 3 [90%]: train=5728 | val=1431 | test=795
Fold 4 [ 1%]: train=63 | val=15 | test=8
Fold 4 [ 2%]: train=127 | val=31 | test=17
Fold 4 [ 3%]: train=190 | val=47 | test=26
Fold 4 [ 4%]: train=254 | val=63 | test=35
Fold 4 [ 5%]: train=318 | val=79 | test=44
Fold 4 [ 6%]: train=381 | val=95 | test=53
Fold 4 [ 7%]: train=445 | val=111 | test=61
Fold 4 [ 8%]: train=509 | val=127 | test=70
Fold 4 [ 9%]: train=572 | val=143 | test=79
Fold 4 [10%]: train=636 | val=159 | test=88
Fold 4 [20%]: train=1273 | val=318 | test=176
Fold 4 [30%]: train=1909 | val=477 | test=265
Fold 4 [40%]: train=2546 | val=636 | test=353
Fold 4 [50%]: train=3182 | val=795 | test=442
Fold 4 [60%]: train=3819 | val=954 | test=530
Fold 4 [70%]: train=4455 | val=1113 | test=618
Fold 4 [80%]: train=5092 | val=1272 | test=707
Fold 4 [90%]: train=5728 | val=1431 | test=795
Fold 5 [ 1%]: train=63 | val=15 | test=8
Fold 5 [ 2%]: train=127 | val=31 | test=17
Fold 5 [ 3%]: train=190 | val=47 | test=26
Fold 5 [ 4%]: train=254 | val=63 | test=35
Fold 5 [ 5%]: train=318 | val=79 | test=44
Fold 5 [ 6%]: train=381 | val=95 | test=53
Fold 5 [ 7%]: train=445 | val=111 | test=61
Fold 5 [ 8%]: train=509 | val=127 | test=70
Fold 5 [ 9%]: train=572 | val=143 | test=79
Fold 5 [10%]: train=636 | val=159 | test=88
Fold 5 [20%]: train=1273 | val=318 | test=176
Fold 5 [30%]: train=1909 | val=477 | test=265
Fold 5 [40%]: train=2546 | val=636 | test=353
Fold 5 [50%]: train=3182 | val=795 | test=442
Fold 5 [60%]: train=3819 | val=954 | test=530
Fold 5 [70%]: train=4455 | val=1113 | test=618
Fold 5 [80%]: train=5092 | val=1272 | test=707
Fold 5 [90%]: train=5728 | val=1431 | test=795
Fold 6 [ 1%]: train=63 | val=15 | test=8
Fold 6 [ 2%]: train=127 | val=31 | test=17
Fold 6 [ 3%]: train=190 | val=47 | test=26
Fold 6 [ 4%]: train=254 | val=63 | test=35
Fold 6 [ 5%]: train=318 | val=79 | test=44
Fold 6 [ 6%]: train=381 | val=95 | test=53
Fold 6 [ 7%]: train=445 | val=111 | test=61
Fold 6 [ 8%]: train=509 | val=127 | test=70
Fold 6 [ 9%]: train=572 | val=143 | test=79
Fold 6 [10%]: train=636 | val=159 | test=88
Fold 6 [20%]: train=1273 | val=318 | test=176
Fold 6 [30%]: train=1909 | val=477 | test=265
Fold 6 [40%]: train=2546 | val=636 | test=353
Fold 6 [50%]: train=3182 | val=795 | test=442
Fold 6 [60%]: train=3819 | val=954 | test=530
Fold 6 [70%]: train=4455 | val=1113 | test=618
Fold 6 [80%]: train=5092 | val=1272 | test=707
Fold 6 [90%]: train=5728 | val=1431 | test=795
Fold 7 [ 1%]: train=63 | val=15 | test=8
Fold 7 [ 2%]: train=127 | val=31 | test=17
Fold 7 [ 3%]: train=190 | val=47 | test=26
Fold 7 [ 4%]: train=254 | val=63 | test=35
Fold 7 [ 5%]: train=318 | val=79 | test=44
Fold 7 [ 6%]: train=381 | val=95 | test=53
Fold 7 [ 7%]: train=445 | val=111 | test=61
Fold 7 [ 8%]: train=509 | val=127 | test=70
Fold 7 [ 9%]: train=572 | val=143 | test=79
Fold 7 [10%]: train=636 | val=159 | test=88
Fold 7 [20%]: train=1273 | val=318 | test=176
Fold 7 [30%]: train=1909 | val=477 | test=265
Fold 7 [40%]: train=2546 | val=636 | test=353
Fold 7 [50%]: train=3182 | val=795 | test=442
Fold 7 [60%]: train=3819 | val=954 | test=530
Fold 7 [70%]: train=4455 | val=1113 | test=618
Fold 7 [80%]: train=5092 | val=1272 | test=707
Fold 7 [90%]: train=5728 | val=1431 | test=795
Fold 8 [ 1%]: train=63 | val=15 | test=8
Fold 8 [ 2%]: train=127 | val=31 | test=17
Fold 8 [ 3%]: train=190 | val=47 | test=26
Fold 8 [ 4%]: train=254 | val=63 | test=35
Fold 8 [ 5%]: train=318 | val=79 | test=44
Fold 8 [ 6%]: train=381 | val=95 | test=53
Fold 8 [ 7%]: train=445 | val=111 | test=61
Fold 8 [ 8%]: train=509 | val=127 | test=70
Fold 8 [ 9%]: train=572 | val=143 | test=79
Fold 8 [10%]: train=636 | val=159 | test=88
Fold 8 [20%]: train=1273 | val=318 | test=176
Fold 8 [30%]: train=1909 | val=477 | test=265
Fold 8 [40%]: train=2546 | val=636 | test=353
Fold 8 [50%]: train=3182 | val=795 | test=442
Fold 8 [60%]: train=3819 | val=954 | test=530
Fold 8 [70%]: train=4455 | val=1113 | test=618
Fold 8 [80%]: train=5092 | val=1272 | test=707
Fold 8 [90%]: train=5728 | val=1431 | test=795
Fold 9 [ 1%]: train=63 | val=15 | test=8
Fold 9 [ 2%]: train=127 | val=31 | test=17
Fold 9 [ 3%]: train=190 | val=47 | test=26
Fold 9 [ 4%]: train=254 | val=63 | test=35
Fold 9 [ 5%]: train=318 | val=79 | test=44
Fold 9 [ 6%]: train=381 | val=95 | test=53
Fold 9 [ 7%]: train=445 | val=111 | test=61
Fold 9 [ 8%]: train=509 | val=127 | test=70
Fold 9 [ 9%]: train=572 | val=143 | test=79
Fold 9 [10%]: train=636 | val=159 | test=88
Fold 9 [20%]: train=1273 | val=318 | test=176
Fold 9 [30%]: train=1909 | val=477 | test=265
Fold 9 [40%]: train=2546 | val=636 | test=353
Fold 9 [50%]: train=3182 | val=795 | test=442
Fold 9 [60%]: train=3819 | val=954 | test=530
Fold 9 [70%]: train=4455 | val=1113 | test=618
Fold 9 [80%]: train=5092 | val=1272 | test=707
Fold 9 [90%]: train=5728 | val=1431 | test=795
Fold 10 [ 1%]: train=63 | val=15 | test=8
Fold 10 [ 2%]: train=127 | val=31 | test=17
Fold 10 [ 3%]: train=190 | val=47 | test=26
Fold 10 [ 4%]: train=254 | val=63 | test=35
Fold 10 [ 5%]: train=318 | val=79 | test=44
Fold 10 [ 6%]: train=381 | val=95 | test=53
Fold 10 [ 7%]: train=445 | val=111 | test=61
Fold 10 [ 8%]: train=509 | val=127 | test=70
Fold 10 [ 9%]: train=572 | val=143 | test=79
Fold 10 [10%]: train=636 | val=159 | test=88
Fold 10 [20%]: train=1273 | val=318 | test=176
Fold 10 [30%]: train=1909 | val=477 | test=265
Fold 10 [40%]: train=2546 | val=636 | test=353
Fold 10 [50%]: train=3182 | val=795 | test=442
Fold 10 [60%]: train=3819 | val=954 | test=530
Fold 10 [70%]: train=4455 | val=1113 | test=618
Fold 10 [80%]: train=5092 | val=1272 | test=707
Fold 10 [90%]: train=5728 | val=1431 | test=795

Done! All folds and percentages saved.

In [ ]:
"""
Creates the folder structure required by Finetuning_SciBert.ipynb:

    spin-off/dataset/fold_{fold}/10-fold_original_{percent}_percent/
    ├── algocite_utilize_dataset_train_fold_{fold}.csv
    ├── algocite_utilize_dataset_val_fold_{fold}.csv
    └── algocite_utilize_dataset_test_fold_{fold}.csv

Source:
    dataset/10-fold_labeled_increasing_relabel_ver3/
    ├── algocite_utilize_dataset_train_fold_{fold}.csv
    ├── algocite_utilize_dataset_val_fold_{fold}.csv
    └── algocite_utilize_dataset_test_fold_{fold}.csv
"""

import os
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

INPUT_DIR    = './10_fold_dataset/10-fold_labeled_final/10-fold_labeled_increasing_relabel_ver3'
OUTPUT_BASE  = './spin-off/final_dataset'
LABEL_COL    = 'UTILIZE_LABELS'
RANDOM_STATE = 42
PERCENTAGES  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40, 50, 60, 70, 80, 90]
N_FOLDS      = 10

sampler = StratifiedShuffleSplit(n_splits=1, test_size=0.01, random_state=RANDOM_STATE)

for fold in range(1, N_FOLDS + 1):

    print(f"\n{'='*55}")
    print(f"FOLD {fold}")
    print(f"{'='*55}")

    # Load base fold files
    train_df = pd.read_csv(f'{INPUT_DIR}/algocite_utilize_dataset_train_fold_{fold}.csv')
    val_df   = pd.read_csv(f'{INPUT_DIR}/algocite_utilize_dataset_val_fold_{fold}.csv')
    test_df  = pd.read_csv(f'{INPUT_DIR}/algocite_utilize_dataset_test_fold_{fold}.csv')

    # Get shuffled stratified indices for each split (same as paper)
    for train_index, _ in sampler.split(train_df, train_df[LABEL_COL]):
        pass
    for val_index, _ in sampler.split(val_df, val_df[LABEL_COL]):
        pass
    for test_index, _ in sampler.split(test_df, test_df[LABEL_COL]):
        pass

    for percent in PERCENTAGES:
        ratio = percent / 100.0

        # Sequential slice — smaller % is always subset of larger %
        train_sub = train_df.iloc[train_index[:int(len(train_index) * ratio)]]
        val_sub   = val_df.iloc[val_index[:int(len(val_index) * ratio)]]
        test_sub  = test_df.iloc[test_index[:int(len(test_index) * ratio)]]

        # Exact path the finetuning notebook expects
        out_dir = f'{OUTPUT_BASE}/fold_{fold}/10-fold_original_{percent}_percent'
        os.makedirs(out_dir, exist_ok=True)

        train_sub.to_csv(f'{out_dir}/algocite_utilize_dataset_train_fold_{fold}.csv', index=False)
        val_sub.to_csv(  f'{out_dir}/algocite_utilize_dataset_val_fold_{fold}.csv',   index=False)
        test_sub.to_csv( f'{out_dir}/algocite_utilize_dataset_test_fold_{fold}.csv',  index=False)

        tl = train_sub[LABEL_COL].value_counts()
        print(f'  [{percent:>2}%] '
              f'train={len(train_sub):>4} '
              f'(UTILIZE={tl.get("UTILIZE",0):>3}, '
              f'NOTUTILIZE={tl.get("NOTUTILIZE",0):>3}) | '
              f'val={len(val_sub):>3} | '
              f'test={len(test_sub):>3}')

print('\n' + '='*55)
print('Done! Final structure:')
print('='*55)
for fold in range(1, N_FOLDS + 1):
    for percent in PERCENTAGES:
        path = f'{OUTPUT_BASE}/fold_{fold}/10-fold_original_{percent}_percent'
        files = os.listdir(path)
        print(f'  fold_{fold}/10-fold_original_{percent}_percent/ → {len(files)} CSVs')